<?php
/**
 * Talentis — configuration TEMPLATE.
 *
 * DO NOT EDIT THIS FILE ON THE SERVER. Copy it to `config.php`, fill in your
 * real values there, and leave this template alone so you always have a clean
 * reference.
 *
 * WHERE TO PUT config.php
 * -----------------------
 * Put it ONE LEVEL ABOVE public_html, so a web request can never fetch it even
 * if PHP stops running for some reason:
 *
 *     /home/uXXXXXXX/talentis-config.php      <-- the real file, private
 *     /home/uXXXXXXX/public_html/api/...      <-- the code that reads it
 *
 * bootstrap.php looks above the web root first and only falls back to a local
 * copy. If you must keep it beside the code, the .htaccess in this folder
 * blocks direct access to it, but above the web root is genuinely safer.
 *
 * NEVER commit config.php to git and never paste its contents into a chat.
 */

return [

    // -- Database -----------------------------------------------------------
    // From hPanel -> Databases -> MySQL Databases. On Hostinger shared hosting
    // the host is almost always 'localhost'.
    'db' => [
        'host'     => 'localhost',
        'name'     => 'uXXXXXXXX_talentis',
        'user'     => 'uXXXXXXXX_admin',
        'password' => 'PUT-YOUR-DATABASE-PASSWORD-HERE',
        'charset'  => 'utf8mb4',
    ],

    // -- Where the dashboard is served from --------------------------------
    // Used to reject cross-site requests. Include the scheme, no trailing
    // slash. While testing on the temporary Hostinger address, put that here,
    // then change it to https://admin.mytalentis.in when you attach the
    // subdomain. Multiple entries are allowed during a switchover.
    'allowed_origins' => [
        'https://admin.mytalentis.in',
        // 'https://your-temp-name.hostingersite.com',
    ],

    // -- Business rules ----------------------------------------------------
    // Kept here rather than hard-coded so a change is one edit in one place.
    // The 10% is expressed as a divisor: 10 means "one tenth of CTC".
    'fees' => [
        'registration'        => 5000,
        'placement_divisor'   => 10,
        // GST is not charged today. If you register for GST, set this to 18
        // and every figure the API returns will include it.
        'gst_percent'         => 0,
    ],

    // -- Security ----------------------------------------------------------
    'security' => [
        // Failed sign-ins before the account rests, and for how many minutes.
        'max_failed_attempts' => 6,
        'lockout_minutes'     => 15,
        // Session idle timeout in minutes.
        'session_minutes'     => 240,
        // Set false ONLY if testing over plain http. Must be true in production
        // or the session cookie will travel unencrypted.
        'require_https'       => true,
    ],

    // -- Diagnostics -------------------------------------------------------
    // Leave false in production. When true, API errors include the underlying
    // message, which is useful while setting up and a gift to an attacker
    // afterwards.
    'debug' => false,
];
